version: '3.8'

services:
  mariadb:
    image: 'mariadb:10.7.1'
    restart: always
    environment:
      - MARIADB_PASSWORD=changeme
      - MARIADB_ROOT_PASSWORD=changeme
      - MARIADB_USER=admin
      - MARIADB_DATABASE=grafana-temperature

  grafana:
    image: 'grafana/grafana:8.2.0'
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mariadb

  reader:
    image: 'node:17.2.0'
    restart: always
    volumes:
      - ./src:/usr/app/
      - /usr/app/node_modules
    command: node /usr/app/hello.js
    depends_on:
      - mariadb
